version: '3.8'

services:


  postgres_eddy:
    image: postgres
    restart: always
    ports:
      - "7500:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root


  pgadmin_eddy:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "70:80"
    depends_on:
      - postgres_eddy
